### ISSUE TITLE
Nicht verkaufbar in Kombination mit Place, Terraform & Paint Anywhere

### ISSUE THREAD

**Issue by Spiderschwein90** [Achimobil/FS25_DigitalDisplay#2]
Hi, 

die Digitalen Display lassen sich mit oben genanntem Mod überall platzieren, allerdings dann nicht mehr verkaufen. 
Bei allen anderen Gebäude, Silos, Produktionen etc. ist dies noch möglich. 
Unklar, ob dies an den Displays liegt oder an "Place, Terraform & Paint Anywhere". 

Grüße

**Comment by Spiderschwein90** [comment]
Nachtrag: bei gekauftem Land klappt es ohne Probleme. Bei "fremdem" Land besteht das Problem

**Comment by Achimobil** [comment]
Dagegen kann ich nichts machen. Überall wo man standard Platzieren kann kann man auch wieder weg reißen. 
Dann mitte an den entsprechenden Mod wenden, den den mod den ich kenne, der heißt anders.
