### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Boblerenard** [Achimobil/FS25_DigitalDisplay#4]
Good morning,
I installed this mod on an FS25 multiplayer server but after about twenty minutes the server lag more and more.
I uninstalled the mod and the server works fine.
It's a shame because this mod is very interesting.

Thanks anyway.

**Comment by Achimobil** [comment]
We use it self on the server and have no problem.
For reproduce anything I would need the log of the server and one player where it lags. 
Then I can try to find a reason
